spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8000/realms/dungeon
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/auth/realms/dungeon/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/dungeon_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration

server:
  port: 8080

logging:
  level:
    root: INFO